language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt


env: DJANGO_SETTINGS_MODULE="PurBeurre.settings.travis"

addons:
  firefox: latest

services:
  - postgresql

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - geckodriver --version
  - export MOZ_HEADLESS=1

script:
  - ./manage.py test

branches:
  only:
    - staging
