language: python
python:
  - '3.6'

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  firefox: latest


env: 
  global:
    - TRAVIS_PROD=http://161.35.153.11/
  jobs:
    - DJANGO_SETTINGS_MODULE="PurBeurre.settings.travis" MOZ_HEADLESS=1

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - geckodriver --version
  - export MOZ_HEADLESS=1

script:
  - ./manage.py migrate
  - ./manage.py travis_tests
  - ./manage.py test search_food/

branches:
  only:
    - staging
