# Generated by Django 2.2.6 on 2019-10-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191022_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_product_json',
        ),
    ]
