# Generated by Django 2.2.6 on 2019-11-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20191029_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituteproduct',
            name='nutriscore',
            field=models.IntegerField(),
        ),
    ]
