# Generated by Django 2.2.6 on 2019-11-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20191104_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_test',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
