# Generated by Django 2.2.6 on 2019-11-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20191105_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='barcode',
        ),
    ]
