# Generated by Django 2.2.6 on 2019-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20191105_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='barcode',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='product_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
