# Generated by Django 2.2.7 on 2019-12-03 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('nutriscore', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('barcode', models.BigIntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='SubstituteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('nutriscore', models.IntegerField()),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('barcode', models.BigIntegerField()),
                ('image', models.CharField(max_length=200)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_food.Product')),
            ],
            options={
                'verbose_name_plural': 'Substitute products',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('barcode', models.BigIntegerField()),
                ('product_associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_food.SubstituteProduct')),
                ('user_associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorites',
            },
        ),
    ]
