# Generated by Django 2.2.7 on 2019-12-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
