# Generated by Django 2.2.7 on 2019-12-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_food', '0002_product_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituteproduct',
            name='in_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
