# Generated by Django 2.2.7 on 2019-12-03 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_food', '0003_substituteproduct_in_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_associate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_food.Product'),
        ),
    ]
