# Generated by Django 2.2.7 on 2020-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_food', '0004_auto_20191203_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
