# Generated by Django 2.2.7 on 2020-11-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_food', '0005_favorite_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=200)),
                ('language_name', models.CharField(max_length=200)),
            ],
        ),
    ]
