# Generated by Django 2.2.6 on 2019-10-22 09:13
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=200)),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('barcode', models.IntegerField()),
                ('id_product_json', models.IntegerField()),
                ('category', models.ManyToManyField(to='database.Category')),
            ],
        ),
    ]
