# Generated by Django 2.2.6 on 2019-10-29 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0009_subsitutecompare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('user_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='SubsituteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Substitute categories',
            },
        ),
        migrations.CreateModel(
            name='SubsituteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=200)),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('barcode', models.BigIntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Substitute products',
            },
        ),
        migrations.DeleteModel(
            name='SubsituteCompare',
        ),
        migrations.AddField(
            model_name='subsitutecategory',
            name='product_subsitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.SubsituteProduct'),
        ),
    ]
