# Generated by Django 2.2.6 on 2019-11-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_product_category_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitutecategory',
            name='product_subsitute',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_associated',
            new_name='user_associate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_test',
            new_name='category',
        ),
        migrations.AddField(
            model_name='favorite',
            name='barcode',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='product_associate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.SubstituteProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substituteproduct',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substituteproduct',
            name='original',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='substituteproduct',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubstituteCategory',
        ),
    ]
