# Generated by Django 2.2.7 on 2019-12-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20191105_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_associate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
        ),
    ]
