# Generated by Django 2.2.7 on 2019-12-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20191202_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituteproduct',
            name='in_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
