# Generated by Django 2.2.7 on 2019-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_substituteproduct_in_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
